apiVersion: v1
kind: Secret
metadata:
    name: kite-secrets
    namespace: kite
type: Opaque
stringData:
    JWT_SECRET: ENC[AES256_GCM,data:qSWnYi7vdd39z0LiytlFUJCY1KHUvROhjIrO,iv:eGUJZBb+YraAlZDf0qLOzsmkEBzrpzDUNv15NdCoca4=,tag:ytUsW87qDcULWPRoZhrMCA==,type:str]
    KITE_ENCRYPT_KEY: ENC[AES256_GCM,data:uESAg1lNUDFATt0Z6ICXLTcULIrqyA2LkadnGzM=,iv:FbgrvRrouRLEXj5aA8AzO1Y/S0muIq/08U6T0klKnzE=,tag:6DUTBE9kKPY2H/JSHEOK2w==,type:str]
    DB_TYPE: ENC[AES256_GCM,data:+yGyqCfZvss=,iv:7QEZt3Pw7WQEBsvvyL7+5YTQkW6VcN1qdvHAzcNKtSA=,tag:HTTegfB4O/mTiSUyGEo1cA==,type:str]
    DB_DSN: ENC[AES256_GCM,data:KmYoBRapgthjjopOB/yw5BRDy5K08H71UHsGcbll5UsE7WoOjpOv7ehVKo1l9jjxS1Jw4jf5UOx1gITsSbFanpI7h0xeyO4dV6v2Q71Nz+7Ly6iltOhukm9Oow==,iv:YeRTYAeHG8SSNOqXTEISFwQ48kUooFkhsxjwS7SJx2g=,tag:YwncgmfIUy9nUpwbeFv7oQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeC9ERGVaYjhYT3c4ZXVs
            dlJpSzJtcUxFQ29lOUx2ZXRSZ1F1MUZtSW1RCnNLbU15VkswdUduR1N0UThkTis1
            QlhXMDdkOXN0NVI0bk41a0Q2TUNkQzQKLS0tIGt1cC9IRk8yaGVjTVNLeFBDaUlW
            eHRZQ1ArakJZYnowbnh0ZlBwZ05uYmMKX+I4giBPiDLbbx04EQL3hkwk5qIB9tbf
            fS7447l+DW3zsccbA6K8XbcJk0Lh3dtasUd+6symfl1yA+5ON608tg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcTQ5KzFQWDNyeXAwTjlX
            eUlHVkduTUxIZXZSUDBSVStpRzUrYU83bmprCnl4aU56dVZVZHZ0K2xCOEZBZjly
            Qm9iMmdXMVVqalN2SHFlanFmclR2ck0KLS0tIFMxR2xEZUhBSk0wQm9CcW9yVnBT
            UTNmRUlyWGRkNE1XUXBiT1gyUm9rMW8KrSgVxZ60vEhPCoBrQWXBBYTis0e/O8OM
            caahYWb7vfIl4tL1aEAGNxW4bPXzFTlKvR+oKlfu/U9sqoXjMz22Fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T11:08:51Z"
    mac: ENC[AES256_GCM,data:WNx3Ns1BFCoO8fz1HUnQ28oe6sfECdhcoYcy0ZrU06djeJxLECNZPE/No4TPXfOPXNwiP5i7EhClrJ5u6otzoMGTOxCy8C1X6bDrY+7Hjp9Hhtul1AG3phKmIiEJtdjQ/f2V6A1GC3rn02+/9w+4kzkw6fafElwPhrQTiA9jxxI=,iv:GNsD0Nk+sh95eULo+cz0yP1e2FGE9fRG/sYz0KMYRfE=,tag:0zxrYPgLby20wql3xH//rA==,type:str]
    version: 3.13.0
