apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - kite-secrets.sops.yaml
  - postgresql-credentials.sops.yaml
  - postgresql-helmrepository.yaml
  - postgresql-helmrelease.yaml
  - helmrepository.yaml
  - helmrelease.yaml
