apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: kite
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:jiGVZSRIFLiw0oIbSnh1050vNmhqwLjH6TfqbY5L,iv:yVnlWWXWYbJQwnBnHhhfmlsUD28UBVSDbYRTJtZhSvk=,tag:zqOGLzOK+EQGliAFPkpH0w==,type:str]
    password: ENC[AES256_GCM,data:9HRaOSOIOJziLpFFzQU3/o3ojXUAP8S37/76WyPRzQ==,iv:nyTKPSvSoyz2uT46FDsyKyffHs/x6KkMTMoKevUMDmA=,tag:HDjSAxv0V1JUnUSjPH8mOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrakF2dlJzTjRCeDdIMFhV
            QWNnd1NoZ2M3cUllSmVaeWhIVFRYaHo5d1ZjCjJRSVpKU3lvVHpIb2FraEl3VFYw
            ai9zc05RNlcxYmFtaE9oRDkrSEhxeEkKLS0tIEtaUERGMW0zanJkbXMxSW1oN1Rj
            V0wrYkdWTTNDZUdUdE9IaUJnOGRFb2MKXPEiVlYv2t8VnAeszx+KHylV7VQx2moX
            9R4Ib7u1h4yzd6xYfRLvsvyEsK2hkpU/qMvjZer8WKAinbvG9DoydA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUOHFwNDJyWDN5aHB6Z0hx
            OWxOZ0xOV2dqRFA5SEJIYXU3V3hkWlR5bkR3CnZ6Ym9Nb1ZDT0ZnS0k4NkdlckFh
            cC9KWDNYWlZ5T2RaZDZyNEtvRFFsazQKLS0tIDZMSFZNT0ZKYWRzYUpkV04rNnUy
            V1FDL0ZhRCtHalBwN2xlOHdmcEJvYjQKR6316kIhWkM1Ngqg5wlsnluoAIjll5CW
            MRTJVlNKMS6/qletex4hIgDJha29Th+yu03XudV9O01pmejZn85I2w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T11:05:42Z"
    mac: ENC[AES256_GCM,data:sHaGBmxNMrWxokdGs5SkvKf7IWLjbiFwD1XajwdXEhg9Plf+jfZgTKTwnsq5uSDXdFoAd7Z6SfKhHyb5QC0ASlLgf8QyV4LoYdYfFaWGsdWKQK12F4ie5j78F32mOa817eL7jHh+QbtlMjd/EgO6fJu4LKB4JzCX6sYSm8RWXr4=,iv:7WrCQCM0F8FhLCyfrgLY1yjEJnYN0V9JwKqI0zBK2xE=,tag:R4WdNgcvDvbPs0ngqJcrVg==,type:str]
    version: 3.13.0
