apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - datasources.yaml
  - dashboards/sisyphus-overview.yaml
  - alerts/platform-alerts.yaml
  - monitors/platform-podmonitors.yaml
  - monitors/cilium-servicemonitors.yaml
  - network-policy.yaml
