apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system
  - cloudflare-tunnel.yaml
  - storage.yaml
  - cilium.yaml
  - observability.yaml
  - observability-config.yaml
  - kite.yaml
  - portfolio-staging.yaml
