apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cloudflared
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - cloudflare-tunnel
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-controllers
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - kustomize-controller
          - notification-controller
          - source-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
      interval: 30s
