apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - job.yaml
  - network-policy.yaml
configMapGenerator:
  - name: searxng-evaluation
    namespace: malg
    files:
      - evaluate.py
      - queries.txt
