apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgresql-credentials.sops.yaml
  - malg-runtime.sops.yaml
  - runtime-config.yaml
  - postgresql-pvc.yaml
  - postgresql-service.yaml
  - postgresql-statefulset.yaml
  - searxng-settings.yaml
  - searxng-deployment.yaml
  - searxng-service.yaml
  - lightpanda-deployment.yaml
  - lightpanda-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - network-policy.yaml
