apiVersion: v1
kind: Secret
metadata:
    name: malg-runtime
    namespace: malg
type: Opaque
stringData:
    MALG_LLM__API_KEY: ENC[AES256_GCM,data:SN2tj36A+3sp7gC7631T9+NV7gmpQEAPyA==,iv:yVQzxA235K2flXMERAfzQTinosy7RZLFW5NyYocY/xc=,tag:rZcwaG1n3qkqKARmvPKHzg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:FIPmf2VrvrwB1ijLTKb/FjPb5jLvKgUPqeNqk5cHX1DTChs0j481XsNGH4j4UrV/qTlDcs99AZjyZR3nwgdqAA==,iv:KeoTcnHQr/tDJqjoKNRAwCae3lfEoESHidNdrdf8TKk=,tag:+2TgbHXzWEDCpcxx5s+7BQ==,type:str]
    MALG_AUTH__PASSWORD: ENC[AES256_GCM,data:HrsCJU+iJDc9iskOISXVPQ==,iv:sGcq2mho98RE5HrXZn2qDgpXphRLzEyWrrJOPoYPke8=,tag:kpU0xXQu+r3vFbn+n9kf4w==,type:str]
    MALG_TWENTY__API_KEY: ENC[AES256_GCM,data:HI4lWV+BR+DBeT6pboBva9dlQte66DQMIxg0LzHlpJgpMep/8z+iEaf4HEznm+7HYAeQJuKAc6S5fAUsE3PK5bf3zAO6EM/b9FJ26jOjTBfrGrZ3l80VdxcFX5fY6QwlcJQPaPJOuLlSBiuwShD6zvGubSEVFB/zP7SEow+OKzaJpGFWOlTk+sbaFcEVUeDfbw2NGTW4dbtOrctdxq/uUtjKMjXHLL8oVGyLW4W62Jy8Ay7Lp3Ox+8btQmlBDfvgcH717rPslXbvSlyDJptGdiIp0vMJlWGte/LPB58jD20GYB83eEiZ3BbY5OGKcPjxRYEv+tdHNFF+Xr4mfc/sQrkNaeI1KjVJejdwM4PClbkeLk48IVCdnY+feFqLsu0gi5VrQmXgEHkmMVy/XCbLgIYHAwtHBfNvPoW9kAdH9o08qBQlimsfb0gd0Eb0ptMV1Wdx+8JiBZLV+8iwTvPDrFmYxX+hM6MU/dvS0VP+BHdF1lykrek+Vc6qmzbAZMU9YKhux8bA/RVI5iQOcjnZPX/EvIzIc4Zn7Pf09QIRo1TpmO5XoZFu+7kGj5oYCBe7gyJn62V4YaZeLZC4,iv:FrGYmE1zsuW5O62DGj0INOegphPpU4wT19AfI8XKw4Q=,tag:jBE/8rqnLtbUQ1RooXg4Kg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHdxcitoSTA1T2tTR2xz
            S2VINTVVbmZid2poR1QvMXNSTzJLSjdRYVVVClVwSHhYZEpBa3R0WDEvZ0doOFds
            cmtPK1pOTklOWDNGRnVZM3dpbnVSUTgKLS0tIGFLbGwwR3oyL0NHL2JWTjNjbG4r
            QnBUOVk0QzZQZU1pK3NlaUdwYlBCMmMKCraoCxYJlUrpCEA1kPMNZE3a6fGKIKvk
            5m6kxzp5X5mnXoQxL4i8is9FEwC+IGK7dP97gTs7GF7G20N3hP749w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRzNVR1RaaFZ0OGdjTHRS
            bVhYNGVZWCs4OXZPYmp0NHpnSlFVYW1vZlYwCmFHSytET2svMXpORVQvK0pOeFdU
            bVNBZnEyN3UzYndsR1ZNby9EQktWeVEKLS0tIHBtY1dZSkxQY3l3Z3VVdUErS0Rk
            UFFpY3Q4QWlHLzZHZjBjQVpub3FPM2MKpxVEvLwP+UrGcWirV7r2yTnaIRadJ/Rv
            Ot5jkH5naufvk4WJ1zipI4u+2WJBD+SVzet+4HLKoU3lbSn0MIPiKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-23T09:57:42Z"
    mac: ENC[AES256_GCM,data:+tawgzO1D2euumVwKWLd7EP2R44IAmKIlqUkGem6g4eUe/HybUgrZQ5FfbNsHKOM3adXFMgIq3SOQSv7vokRqE8jYXoEY/A8Y4EF3bn0Zdfxz57WyWhBg6m8hgOEw8p8yorVVrrahw1nIzcIypXmge/k531lwn7lrlaY5nlVA8Y=,iv:X0y4xfCvo3lklI222GE3L2jI7rUhFPNSz6IopIK7CCE=,tag:RVNNVsOen6uJhGY35JirHg==,type:str]
    version: 3.13.0
