apiVersion: v1
kind: Secret
metadata:
    name: malg-runtime
    namespace: malg
type: Opaque
stringData:
    MALG_LLM__API_KEY: ENC[AES256_GCM,data:SN2tj36A+3sp7gC7631T9+NV7gmpQEAPyA==,iv:yVQzxA235K2flXMERAfzQTinosy7RZLFW5NyYocY/xc=,tag:rZcwaG1n3qkqKARmvPKHzg==,type:str]
    SEARXNG_SECRET: ENC[AES256_GCM,data:FIPmf2VrvrwB1ijLTKb/FjPb5jLvKgUPqeNqk5cHX1DTChs0j481XsNGH4j4UrV/qTlDcs99AZjyZR3nwgdqAA==,iv:KeoTcnHQr/tDJqjoKNRAwCae3lfEoESHidNdrdf8TKk=,tag:+2TgbHXzWEDCpcxx5s+7BQ==,type:str]
    MALG_AUTH__PASSWORD: ENC[AES256_GCM,data:HrsCJU+iJDc9iskOISXVPQ==,iv:sGcq2mho98RE5HrXZn2qDgpXphRLzEyWrrJOPoYPke8=,tag:kpU0xXQu+r3vFbn+n9kf4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNHdxcitoSTA1T2tTR2xz
            S2VINTVVbmZid2poR1QvMXNSTzJLSjdRYVVVClVwSHhYZEpBa3R0WDEvZ0doOFds
            cmtPK1pOTklOWDNGRnVZM3dpbnVSUTgKLS0tIGFLbGwwR3oyL0NHL2JWTjNjbG4r
            QnBUOVk0QzZQZU1pK3NlaUdwYlBCMmMKCraoCxYJlUrpCEA1kPMNZE3a6fGKIKvk
            5m6kxzp5X5mnXoQxL4i8is9FEwC+IGK7dP97gTs7GF7G20N3hP749w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRzNVR1RaaFZ0OGdjTHRS
            bVhYNGVZWCs4OXZPYmp0NHpnSlFVYW1vZlYwCmFHSytET2svMXpORVQvK0pOeFdU
            bVNBZnEyN3UzYndsR1ZNby9EQktWeVEKLS0tIHBtY1dZSkxQY3l3Z3VVdUErS0Rk
            UFFpY3Q4QWlHLzZHZjBjQVpub3FPM2MKpxVEvLwP+UrGcWirV7r2yTnaIRadJ/Rv
            Ot5jkH5naufvk4WJ1zipI4u+2WJBD+SVzet+4HLKoU3lbSn0MIPiKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T22:45:43Z"
    mac: ENC[AES256_GCM,data:8m0i8zFf23r8ehlLNzpx6a7wtboi5KFcLYWtD8mUqY3/08zefDQ+Bs/6uumrxKrp45ad7G6XIpwP/sWKPtKEvkXenHaS3pEX7spi5qvhPecDxF3KiDTCO8QEW2APS73WjSLI5Iq8eabJKQ1lm045+g+l21QKJlY3W6SYKajCapk=,iv:N4k/H8b6kMHTU88IuTlsghIKWdB6sFVIA5XHayFwRuA=,tag:z3uA9wvOJZR8xLTIJjGxmg==,type:str]
    version: 3.13.0
