apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: malg
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:GFmn3w==,iv:QaWdhARqUORk8yAtCU1mHJCd6k6Vcd3POuwOjwRADkc=,tag:Fvz7kKh+mHa2vY1lqX7EGQ==,type:str]
    password: ENC[AES256_GCM,data:+00brm3VNS2y1j9C47Xw6yIos4y73N/pk+dlEHw7NODXcC4PdFbttiDonsYGEWsX,iv:Zo/hwsPE05IgoRm+RozpSoS0nRbhtqF0RkOKmu9XEdQ=,tag:8T9HpjWytgKQdUDXqhOypg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWlE0OUhDTG5pYmNyTmtF
            YVllVjZpU21UN1FFSEczL3RVemVSclh3dFFnCkNKWmR0RUtGNjBBdWRvQlFkeWdL
            eXprS0dCR0MvbE5pc080a0NQd0Z1bDQKLS0tIFJhYmo1UjRrWGMrVjNCVkJPbURk
            Vm5kWW1GcE1iMHp0TU4xd2d2UGtZVzQKMKDgz39KEx7N2P55usL6evOdSI3KzaMR
            laxzs+IDwxbb9hbWLGEr+TfjJHIJoaahK5E7qfYHTB3wXSlMFuIn2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdFIzOFIyeXpUK2dBRklF
            RGRzVjNXMU4wSkNZdVhyUUxjY1NLUzgvZ0Y0ClY4TDJpdVpIMERQWS9WZEg5ZExj
            RmpTeWZpazFESi9LOTI2MUlPRGNpdmcKLS0tIDlzQlpjejFPNUVHeTNnSVMwWlBo
            SmtLUEx0d0lOTzlVK3IvOTRYckZXUlEKzQWQT9wvcEMc/3A5M/TX8mbA0WYqtDmE
            c3chdCksinlL3phQgpcFUeTVcIOqa/C5hdekxGV84DrVvoI5HOvmOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-12T21:42:00Z"
    mac: ENC[AES256_GCM,data:fCOXwIJTMkZ2WVIPQqW5SJwR9Zmr64H3+oIZB9vy3X+9SSMF6lmN3Zg/Xh/YXBzpguUxHivAmmgMMxH5tQaT+b2g8w5inowitF5itiOABRrJXJjTKV3NhWx/zZDDNCy/bna/SVSCdkZm4OKV9yhYot7uouo3ngK6AzxlII9sTRw=,iv:HoU1E5OIoFF6NLlfUdq+LIcWxr+8WsEQ1LmftzTPWtE=,tag:6bQduwPHT1hnT51FGIQIYA==,type:str]
    version: 3.13.0
