apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: twenty
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8bH9H+4OUMYz6xWtlQ+z8Dg=,iv:gextcnfxk/hESvFubv+XJ3fV/wP6nrXPlFcGVw4coCw=,tag:MlPuBEYiofe0e9E0Hj+O0A==,type:str]
    password: ENC[AES256_GCM,data:W81jCRLCuveGmB7zvIuHfph9QhDIPUzlCByLhHSsOORVFdYBaXRNx0joUw==,iv:EO0XlMD2mVTto5pXT7hiWC4HhfrMMRxYIRCjg0+zS8M=,tag:9QDMBZ7oWYTd4Jgws2SlLg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MDhQa2xtb3VIMTVtZXJL
            dGpQNDhkaHBXbVVnVXpMdkx4RzNlbWcyd2swCjhtY0dxK3BEVWVvQmVYcGZvR3Rt
            aDMyeGxObWpDNEdzMFdVcUJYdCsvVWcKLS0tIGdUeG01cENiVEJUWnFpMk8yVmtQ
            MTJpQ0ozMEZnN0NDamhZQzVHYnZ4SjQK0JEchhkV8KSJzEVXLYASyGykWiTCjzAu
            II5DBJ84zyVnpxaz931uySGEEDf+DDeeEyQ3Lo6Xv79mKKkNqL/yjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWEV6TFdJZ3F1NDRYTjNZ
            TUNIL0taVDRpcjZFZi9EL25iVjJEZkhaRW5jCmxsM2IzNVQ4SEgzZy9OZ3Q1NHhp
            YXlVa2ZEamtRZ0RmTUdZYkt3ZGpYYTgKLS0tIFlXcHdGMEM0Tnk0cmxjakc3dFFM
            NW9VVkJIVjVIVEYzSXFLR0toZlJGZFUK3SJ40uuErcOShx1fCWhGBDDMdjlEc2hX
            utX5eBqP3fUgFlVIiL54twvNjI4UXw5m/X9px3fWy2AblT/X8B5jZQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T20:41:29Z"
    mac: ENC[AES256_GCM,data:fYEvik3r4ypO/GHvYXjShmXPQoptR+zKNYMQn8lSfQ3vys+3e3u6IzSsrc5Djri9LeoGy4x75s1yEW8/h2wKi7K9sA1nvFHM9spaHpZ1eCCPRWfL6USbM+0hkMofLG5f6P4pwxEyAb0TdMPM6Mgopo/ZrTN5D3pvcW0H4WJ3Pg0=,iv:xOqC/yFvgcMV+DHdaNpy8+A/PBOxgr8+HQoADdkEK4I=,tag:B6GD5qI5IIyLdHPwDPWZvg==,type:str]
    version: 3.13.0
