apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: twenty
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
    app.kubernetes.io/part-of: twenty
    app.kubernetes.io/component: cache
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
