apiVersion: v1
kind: Service
metadata:
  name: twenty
  namespace: twenty
  labels:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
    app.kubernetes.io/part-of: twenty
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: server
    app.kubernetes.io/instance: server
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
