apiVersion: v1
kind: Secret
metadata:
    name: faster-whisper-runtime
    namespace: litellm
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:GKaT6Lb2vhZ2TIFgsfYdOHm791AnmS6csCGKzCB/WrocTYgiFckvtyD3L8RhMq/ZpUYZE0WwSYZrP/weBKx4AtN/LA==,iv:gqhFaAsdkqIKUj5tno6UzAe3H5RAkc/fq6kuKGm52ps=,tag:CdZnkAmDxN0ieGpVTIICeA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBOFhsLzhIR1k5YitRKzhy
            T2ZnZDVqaWNiR1VVS1g2OG1meDljU0lOa0dnCmdHMy9ldmtOVnE3TmJsTWJXR1B5
            YmZ6TnNKeHNFMG1JdWdsQnFZdFpvS3cKLS0tIHhDaFpDVkFrWW5kT0pnTFhveWdR
            eHhZa1RVU05oNnNvRUpZRmduOXROVmcKOhgcGqAqXFV4WPDlFQW2ZM4/42vpcMLk
            vixOCKGdgJTHEGceE4DZzIE3OqcjekOtkvn/JpwSqIqm2cI6oMy91A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXYjhqMWdoQUlYZUNzcHhQ
            WVB3RjVwYVo5T3ZtbEp6Z0hiOGZTSmpVUW5NCkY3QnVNMkU4UE1jbXNDQ3poeGNM
            M1M3SGxUdEh0Z3c4SFUyZytOclBIQTQKLS0tIFAyMHRYQkNsekxPbkcvZkkvYjA3
            cnA5VGRHU0NJN2wvcDhjam0ySC9yVGcKYZ9vLRY/ewoiN0HLXcW2+J9JU3IPIsZR
            PHb5JR5HZUckOspq/Ap/9VnzkfTN48hfj+K/SPKiYQBEjZVdJdYmdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T16:28:03Z"
    mac: ENC[AES256_GCM,data:VI4uBUNW3Mh8iN9lwXdv4Os1Nyq5AXWg64wOD01QT6RlU//wylr229JcHQS6FmmrOlDVwKkGEe4kWLITeGS0XsSLn0vR6AnmeYB2SqrCLgA4nKiRcUNmOmJcJjBM5jI9pJAh6mktyawBq6Xtoj5jF4DlE1JARspVrIwjeFGLMKs=,iv:QEZ2YwXijSaReG/+KbXCEvv60cb377BKdGaS3Wg4QQ8=,tag:acfM+KEu0sx4kuy0DVZ4xg==,type:str]
    version: 3.13.0
