apiVersion: v1
kind: Secret
metadata:
    name: faster-whisper-runtime
    namespace: litellm
type: Opaque
stringData:
    API_KEY: ENC[AES256_GCM,data:q49uFcvE0wx6rD0sMlAB/M2ZlzvBm3QxtAFVFk4xV0r3SmDIVgfU9cpiSib8YrwqlyfN/GVNRY20NocfRUisIfqlSA==,iv:+TqXTcHcRZ3r3SIqBOLkftmQSwGX3mUlD/Aicp07PvY=,tag:A74C/wMCxhf4mMLy7eImkQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQSsyamYxRCtkSHlzd3Y0
            cnp3cEhTZjM2c2tsWDhKVTVKeGNGSWhZS0hFCm55b2xybDQ3UkhhR3lSZCtqZ0tz
            VmErZEZ5Qmp0UldmazI4V2ZhMUFmRUkKLS0tIHU0b1BDTlBVUCtLZFJuR0dLaEg2
            QVhEK0hRY1ZYVk1rQkFFTldEd2Nmd2sKJjjEwv1c+pQGWRVDZf824uigIHvcJ9Wm
            ZIB18thM2FdMXD/1+xWe2FptZ/5w25/0caL1/XpAAx6N8NmSHpLvqQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPbDc0VFFPYnNVNktiK3RF
            NitqVEg2azlHck51cHVDMXhyTU9UZmdKMmp3CkpWVnJzNmJjU3dDRFYrZFdKNkJP
            SU9UcXlGcE1MSStYMXV0MTFmT3FjZW8KLS0tIG9uT0t5VEhJcVFFVU1MdzZwQ3RP
            c05KSGFoeWw4RzlBRThVcS9adXFQaE0KecYYh3vbAkxi8SFKXipc+rCG4g4WvgQ8
            56z2ztoHSjaDTS8f4BOgQcLa4gloeOC1F3Ouh9qPpH98jLrSyq+k2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T17:00:45Z"
    mac: ENC[AES256_GCM,data:bQ82BqwDxrNleL+fCKqtz+QLD4QerxwbKgpc8z0ArEWHlUm/hJxXlZfyqEUMU52PKWsy5bSLBFtZOuz1+IZ39lQatEln+pavkCcJEYaK+0J7xKaQh+ajm31jdBWZ8BsTMWFksoTUJyOqoRFbFrNXjphhRLSzUSysvGSgUvTt1/A=,iv:ui58LTVAnlvGEARgtHWywO5xBTQMWmztGQuLXMO/z7w=,tag:w1SklNGlLLiPXr8VjgyxoQ==,type:str]
    version: 3.13.0
