apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: postgresql
  namespace: litellm
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/postgresql
  ref:
    tag: 18.12.4
    digest: sha256:be5907fe1e4d70f2dabb0cb2429d3c4476c39c2240df67445950d3909e011070
