apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TvInYnvX+IUc9w/Z/zfzeB6iEica5kEK7YUODWIV8BkfbcqeNTFMy1BYJ7ekUFaN4JDJ9LiFZvGs+JjJZm1bc9LCnfwsYz9dMml8QCI2jWxOby4Z1AoXVQ==,iv:WdBFgJJGD550Hl+hJcDRZ4uBweQ0hj7kpgL1BHymdTU=,tag:k5FdbNQmyQLdvD7ihpu3UQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:47JuUcDXWMFUAPZ43PNd9OMAlcP/42wBzt3uTXqZsKJwAYdNLv/qRCP9uc2r5FAKgfo3R7cKj7qULNPYW/uP9MJwsiOuku0AJoTtFkr+vzleNastxvEfXg==,iv:Djn50l9bPfK/pmKeyLsW3hktc+lKMjUhcbfORKNTzIw=,tag:Bts7mRl3/9fPK32tx6HNbQ==,type:str]
    username: ENC[AES256_GCM,data:eUe8lGgslu01/ZU2,iv:y8o8KhvvdoSBNBdd+rmc2DoX3BsQ6RM2K/VEK/IEnUg=,tag:m0L/Lq/304e9S7IMS7XKHA==,type:str]
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: litellm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU1YvNTgvM2ttZnhvdFlC
            OG5VTThuWi9QeTIwbkx6c2Z3L0l1ZXhIckFBCklpSFU5czhZMXdLQTkrZFdNblNq
            NFFVUGgrWW9tZHJxRVVmdGluUm1lSFUKLS0tIDlzZlZoeFpocnRnYWpFcWpVVHdX
            aU43VUJjZGQ5S0RmWWh3WXErR29zQ2cKP3a1F18WRMd1JNMbJPQ0lL+VhNy8MKXg
            mfj+PkRxmRhHrlEWJKl8qaY1O0o1zTee1AsAOfOT941NAsSFap4XNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVXJBZG5iVEx4Q2x2b2h2
            VElYNFRWU28vWnZKU1g1RmRrbjVadVdEc3k4CjQ2d3BVS1JaWnZWU2xQWGVaQkk2
            ZzVIUkw3UkN5aU5tbkxNTFYxNi9VN0kKLS0tIFVyL3V2VzJVVThrTnl1N2Iyc21k
            NmxrUG0zNjFTSmwrWEsyVTJsUTBud00Ks28Pq3SF9EXnGp6ZKCGxrKrP88IPlNab
            A9/gxzQigeX/iAM64TwBaXyzpC34ciBuWcqXVLU7rZAMiZiB1HrsRA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T14:13:21Z"
    mac: ENC[AES256_GCM,data:DzPAo3m+h25a3QXXv7I1RpcuRBnfr9RkiSFcAAhdln+j/uDDGo5r/Z9Wtx8t3gNCBuSc37u77p3yy03Y8BB/avYjFQrfNM29PgS3+6KvAAL53Tf/QVccZIEEnt6/PyCo+wTdikOFiCCMqSBdw2uHSFuoFGzQrkeMYTyZpWKCrHs=,iv:cm3smQBNQa90KXOY3nUXoeRL5mNxllISvK6X3VvdF6Y=,tag:LbRSLcIL4LrKGRMXa06vhg==,type:str]
    version: 3.13.0
