apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis
  namespace: litellm
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/redis
  ref:
    tag: 28.3.1
    digest: sha256:778d8d31eb0d5b697ec0928bcf4a5abc3a642e0b0c19291ef9bfaa48c40f703a
