apiVersion: v1
data:
    REDIS_PASSWORD: ENC[AES256_GCM,data:5Kei5nzWj9WGxbLo1X7f96k4LYoteLjpb8SeBiBK30tlVeWfz6PanYMLqLDAgpzQ8OF2gdg9Bv9OXcjidOZQIcAQgZHTXsZ3QfYau20PIyQZ65KkHhHb7A==,iv:TVDkU/d0C/E4DsS/LRtp17kdRYDTf+ISLmVciK8y4As=,tag:JP1aWIxsK/cYIANiQWUkUQ==,type:str]
kind: Secret
metadata:
    name: redis-credentials
    namespace: litellm
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSkNwc0hmU3M1MUlYWFlm
            bDNNNXU1TFI3U3YvbVVaZDFWK09meFl3R1dzCjRtajdLMjBKb2JuaFl1OFZjeXhD
            OUE5YkVRbllYa3dOWjYvM3ZMSE5aNkkKLS0tIE4xR3JudVlaT2t0bmdsM0F4WU5q
            dlVEbkJ1UkQrd2gyUk5JYmwvMnBvSlkKhjUqwMOHWI4yr3dE/ssUT1AbJznYcQ74
            6xmLRoCx15Lw8+WbBpX2BsxjsZeY7nEGdLRSkkB9GdKWziSl1r1iKA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18rzcjdhhf4kdfnkjnj7uwmtt36lu5r3kzvdfpdeu78kau73ekqgsfh222y
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFQ2E5QkFMTW52WlFoa1pW
            WmhGZE4rNk9OT0t3eXJvdnorS0YrMkEybERrCmRqRERVYkNzQWk5MEI5VHo0V1Qw
            WHlDSjdrTC9tUFQ0a2VlOUdRV1JEWDgKLS0tIER4bC9hK1VOTzM4ZDFtR2J3WmRU
            cDg5K0hRNTBOTlRxSjZTckloMEhzMTAKJ1I+R6tth/ozD/q2gFdubxqIRF7U+g71
            +MAjAcpzyxp25Kz8CTG2v7wxaUjYRbLNI3kEpCIku/GY/RwLN6tYYw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1z9y7aurkjwxu75dckqnt27f0kds4tecf9m9ctpptg43e9un7vp6qpf8ext
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-08T14:13:21Z"
    mac: ENC[AES256_GCM,data:rQ5lhJu1SBNKDeQ8IbDIGcwteHCgL6OYoqtspqIafO6RFNYwxn2j9dNSvOuIBTJmxiIDkgF80cseRV/fFhUEgwvJhngI9uux54yiebwaPu253pjK4O/hLXnbF2ym5M9r7NUaK+S1IUi9UrTJVS4UWeq9KnBBtGJxIMt+q8Jd87o=,iv:zEo8FI7bLrv0B7AGkNvc4iVqDrg99vkgNP8zTKA3daY=,tag:o3jCrnWE+vSZDWZ9SK9sWw==,type:str]
    version: 3.13.0
